# Generated by Django 4.0 on 2021-12-22 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='date_receita',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 22, 16, 55, 52, 572759)),
        ),
    ]
